apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: emunari/goapp:latest
        # Startup probe to check if the application has started successfully
        # If the startup probe fails, the pod will be restarted
        startupProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          failureThreshold: 10
        # Readiness probe to check if the application is ready to serve traffic
        # If the readiness probe fails, the pod will be removed from service endpoints
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          failureThreshold: 2
          timeoutSeconds: 5
        # Liveness probe to check if the application is still running
        # If the liveness probe fails, Kubernetes will restart the container
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          failureThreshold: 2
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
          requests:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
